---
title: "gganimate slides for manual tours"
author: "Nick Spyrison"
date: "March 2019"
output:
  xaringan::moon_reader:
    css: ["default"]#,"data_viz_theme.css"]
    self_contained: false
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup_pres, include=FALSE,}
knitr::opts_chunk$set(
  eval      = TRUE,  # R code 
  echo      = TRUE, # code
  include   = TRUE,  # plots
  results   = 'asis', # text 'markup' 'asis' 'hold' 'hide'
  message   = F, warning = F, error = F, cache = F, cache.lazy = F,
  collapse  = TRUE,
  comment   = "",
  fig.align = "center"
)

#devtools::install_github("nspyrison/spinifix")
library(spinifex)
library(gganimate) 
```

```{r, results = 'hide', echo = FALSE}
f_dat  <- tourr::rescale(flea[,1:6])
f_cat  <- factor(flea$species)
f_path <- save_history(f_dat, guided_tour(holes()))
f_bas  <- matrix(f_path[,, max(dim(f_path)[3])], ncol=2)
f_mvar <- 5
f_proj <- data.frame(tourr::rescale(f_dat %*% f_bas))
f_ang  <- .2
```

# Structure: array to long df

Given data, $X_{[n,~p]}$
tours projecting down to $d$ are stored as[p, d, n_slides] arrays, but we need a data.frame/tibble!

Data (flea):
```{r}
dim(f_dat)
```

Tour basis array:
```{r}
f_mt <- spinifex::manual_tour(
  basis = f_bas, manip_var = f_mvar, angle = f_ang)
dim(f_mt)
```

Tour basis tibble:
```{r}
f_mt_df <- spinifex::array2df(f_mt, data = f_dat)
dim(f_mt_df$basis_slides) # added frame and lab_abbr
```

Tour projection tibble:
```{r}
dim(f_mt_df$data_slides)  # added frame 
```
]

---

# Plotting

```{r, eval = FALSE}
  ggplot2::ggplot() +
  geom_segment(data = basis_slides,
               aes(x = V1, y = V2, xend = 0, yend = 0, frame = slide)) +
  geom_point(data = data_slides,
             aes(x = V1, y = V2, frame = slide)) +
  gganimate::transition_states(states = slide,
                               transition_length = 0,
                               state_length = 1 / fps)
```

```{r, echo = FALSE, out.height='20%', out.width='20%'}
play_manual_tour(data = f_dat, basis = f_bas, manip_var = 5, 
                 render_type = render_gganimate, cat_var = f_cat)
```
